### ISSUE TITLE
Media Services Live API Collection missing.

### ISSUE THREAD

**Issue by jaescalo** [akamaimike/akamai-api-postman-collections#1]
The following tutorial https://www.youtube.com/watch?v=mIFGKCnBvVs points to this repo for the Media Services Live API Collection, but it seems missing.

**Comment by akamaimike** [comment]
I added the Live Video Workflow Collection and Environment, they contain both Media Services Live and Property Manager API requests. Let me know if that works for you. Note: These were made in October 2020, might have a few inconsistencies if the APIs have been updated since then.

**Comment by jaescalo** [comment]
That was ultra fast! I'll try them out. Thanks Mike!
